/**
 * Draws the Group Network mark and writes every icon asset from one geometry.
 *
 * The mark is the shared circle: three equal members on one ring. Because the
 * same shape has to ship as a vector (tab icon, header) and as bitmaps (Safari
 * and iOS "add to home screen" ignore SVG icons), the geometry lives here once
 * and both forms are generated from it — hand-exported bitmaps drift.
 *
 *   node scripts/render-icons.mjs
 */
import { deflateSync } from 'node:zlib';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

/* ---------------------------------------------------------------- geometry */

// Everything is expressed in the 32x32 units of the SVG viewBox.
const BOX = 32;
const RING_R = 8.9;
const NODE_R = 3.6;
const STROKE = 3.0;
const CAP = STROKE / 2;
// Clear space between a node's edge and the round cap of the arc beside it.
// This gap is what makes the mark read as members-on-a-ring rather than a blob,
// so it is set in absolute units and the arc sweeps are derived from it.
const GAP = 1.5;
const CORNER = 7;

const NODE_ANGLES = [90, 210, 330];
// Angular padding that puts the cap centre GAP away from the node's edge,
// measured along the chord between them.
const PAD = 2 * degrees(Math.asin((NODE_R + CAP + GAP) / (2 * RING_R)));
const ARCS = NODE_ANGLES.map((a) => [a + PAD, a + 120 - PAD].map(wrap));

// Vertically the mark is bottom-heavy: the lower arc bulges past the two lower
// nodes, while the top node sets the ceiling. Centre the resulting bounds.
const TOP = RING_R + NODE_R;
const BOTTOM = RING_R + CAP;
const CY = BOX / 2 + (TOP - BOTTOM) / 2;
const CX = BOX / 2;

const NODES = NODE_ANGLES.map((a) => onRing(a));

function degrees(rad) { return (rad * 180) / Math.PI; }
function wrap(deg) { return ((deg % 360) + 360) % 360; }
function onRing(deg, r = RING_R) {
  const rad = (deg * Math.PI) / 180;
  return { x: CX + r * Math.cos(rad), y: CY - r * Math.sin(rad) };
}

/* -------------------------------------------------------------------- SVG  */

const BG = '#0b0d12';
const FG = '#6ee7d1';
const round = (n) => Number(n.toFixed(3));

function arcPaths() {
  return ARCS.map(([start, end]) => {
    const a = onRing(start);
    const b = onRing(end);
    // Sweep flag 0: increasing angle runs counter-clockwise on screen.
    return `M${round(a.x)} ${round(a.y)}A${RING_R} ${RING_R} 0 0 0 ${round(b.x)} ${round(b.y)}`;
  });
}

function svg({ tile, colour }) {
  const paint = colour ?? 'currentColor';
  const body = [
    tile ? `  <rect width="${BOX}" height="${BOX}" rx="${CORNER}" fill="${BG}" />` : null,
    `  <g fill="none" stroke="${paint}" stroke-width="${STROKE}" stroke-linecap="round">`,
    ...arcPaths().map((d) => `    <path d="${d}" />`),
    '  </g>',
    `  <g fill="${paint}">`,
    ...NODES.map((n) => `    <circle cx="${round(n.x)}" cy="${round(n.y)}" r="${NODE_R}" />`),
    '  </g>',
  ].filter(Boolean);

  const note = tile
    ? `    Primary variant: teal glyph on the app background, for the browser tab and
    anywhere the mark needs its own tile.`
    : `    Glyph only, no tile. Also used as a CSS mask, so the colour comes from
    whatever paints it — that is what makes the monochrome variant free.`;

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${BOX} ${BOX}" width="${BOX}" height="${BOX}" role="img" aria-label="Group Network">
  <title>Group Network</title>
  <!--
    Generated by scripts/render-icons.mjs — edit the geometry there, not here.

    The shared circle: three equal members on one ring, none privileged. The
    glyph stays single-colour on purpose. Teal and violet mean person and agent
    inside the product; the mark says the opposite thing, which is that they are
    members on the same terms.

${note}
  -->
${body.join('\n')}
</svg>
`;
}

/* -------------------------------------------------------------------- PNG  */

const BG_RGB = [0x0b, 0x0d, 0x12];
const FG_RGB = [0x6e, 0xe7, 0xd1];

const dist = (x, y, cx, cy) => Math.hypot(x - cx, y - cy);

function inGlyph(x, y) {
  for (const n of NODES) if (dist(x, y, n.x, n.y) <= NODE_R) return true;

  const d = dist(x, y, CX, CY);
  const onStroke = Math.abs(d - RING_R) <= CAP;
  const deg = wrap(degrees(Math.atan2(CY - y, x - CX)));

  for (const [start, end] of ARCS) {
    // An arc may straddle 0 degrees, so test the sweep in both orientations.
    const within = start <= end ? deg >= start && deg <= end : deg >= start || deg <= end;
    if (onStroke && within) return true;
    for (const a of [start, end]) {
      const e = onRing(a);
      if (dist(x, y, e.x, e.y) <= CAP) return true;
    }
  }
  return false;
}

function inTile(x, y, rounded) {
  if (!rounded) return true;
  const qx = Math.abs(x - BOX / 2) - (BOX / 2 - CORNER);
  const qy = Math.abs(y - BOX / 2) - (BOX / 2 - CORNER);
  if (qx <= 0 || qy <= 0) return true;
  return Math.hypot(qx, qy) <= CORNER;
}

/** 4x4 supersampled render at `size` px; returns raw RGBA. */
function render(size, rounded) {
  const px = Buffer.alloc(size * size * 4);
  const scale = BOX / size;
  const SS = 4;
  const total = SS * SS;
  for (let py = 0; py < size; py++) {
    for (let pxx = 0; pxx < size; pxx++) {
      let tile = 0;
      let glyph = 0;
      for (let sy = 0; sy < SS; sy++) {
        for (let sx = 0; sx < SS; sx++) {
          const x = (pxx + (sx + 0.5) / SS) * scale;
          const y = (py + (sy + 0.5) / SS) * scale;
          if (inTile(x, y, rounded)) tile++;
          if (inGlyph(x, y)) glyph++;
        }
      }
      // Glyph coverage is clipped to the tile, then composited over it.
      const alpha = tile / total;
      const mix = alpha > 0 ? Math.min(glyph, tile) / total / alpha : 0;
      const i = (py * size + pxx) * 4;
      for (let c = 0; c < 3; c++) {
        px[i + c] = Math.round(BG_RGB[c] + (FG_RGB[c] - BG_RGB[c]) * mix);
      }
      px[i + 3] = Math.round(alpha * 255);
    }
  }
  return px;
}

const CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

function png(size, rgba) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // truecolour with alpha
  // Bytes 10-12 stay zero: deflate, adaptive filtering, no interlace.

  // One filter byte (0 = none) in front of each scanline.
  const stride = size * 4;
  const raw = Buffer.alloc((stride + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (stride + 1)] = 0;
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/* ------------------------------------------------------------------ write  */

const outDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'public');
const write = (name, data) => {
  writeFileSync(path.join(outDir, name), data);
  console.log(`wrote public/${name}`);
};

write('mark.svg', svg({ tile: true, colour: FG }));
write('mark-glyph.svg', svg({ tile: false }));
// iOS masks the home-screen icon itself, so that one ships square.
write('apple-touch-icon.png', png(180, render(180, false)));
write('mark-32.png', png(32, render(32, true)));
